name: Prepare environment

inputs:
  python-version:
    required: false
    default: '3.10'
  poetry-version:
    required: false
    default: '1.2.2'
  numpy-version:
    required: false
    default: '1.26.4'
  scipy-version:
    required: false
    default: '1.15.3'
  extras-param:
    required: false
    default: ''

runs:
  using: "composite"

  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Poetry ${{ inputs.poetry-version }}
      uses: abatilo/actions-poetry@v4
      with:
        poetry-version: ${{ inputs.poetry-version }}

    - name: Define a cache for the virtual environment
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-v2-${{ runner.os }}-${{ inputs.python-version }}-${{ inputs.numpy-version }}-${{ inputs.scipy-version }}-${{ inputs.extras-param }}-${{ hashFiles('poetry.lock') }}

    - name: Create the in-project virtualenv if it doesn't exist
      shell: bash
      run: test -d .venv || python -m venv .venv

    - name: Install NumPy ${{ inputs.numpy-version }} and SciPy ${{ inputs.scipy-version }}
      shell: bash
      run: |
        . .venv/bin/activate
        pip install --only-binary :all: \
          numpy==${{ inputs.numpy-version }} \
          scipy==${{ inputs.scipy-version }}

    - name: Install dependencies (excluding numpy and scipy)
      shell: bash
      run: |
        poetry export -f requirements.txt --with dev ${{ inputs.extras-param }} --without-hashes | \
          grep -Ev "^(numpy|scipy)" | \
          ./.venv/bin/pip install -r /dev/stdin --no-deps
        . .venv/bin/activate && pip install -e . --no-deps
        pip freeze
